### ISSUE TITLE
这样的处理不是很好

### ISSUE THREAD

**Issue by Mondaydream** [allenhsu/NSDictionary-NilSafe#4]
这样一种使用场景，我将需要处理Block作为键值和对应的key值存入字典中，读取的时候假如进行判空处理，本来应该为nil的block变成了 nsnull 空值对象，就无法进行判空了，自己的代码也许可以控制，假如引入的第三方不开源库有这样的业务必引起不必要的crash。建议不要使用runtime 来全局 hook，最好还是限制下这段代码的作用域吧。

**Comment by allenhsu** [comment]
的确会有一些问题，但是在没有引入这个 category 的情况下把 nil block 写入 dictionary 本身也会导致 crash。
实际使用中，有一些其他经验：
1. 可以不用 NSNull 作为 placeholder，我们项目中实际是用另一个 MyNull 作为 placeholder，这样在取值时候看到是 MyNull 可以返回 nil。
2. 可以在 production 关掉，debug 状态 assert，beta 状态 alert，这样影响最小，但是可以提前 debug 到 insert nil 的情况。

**Comment by allenhsu** [comment]
@Mondaydream https://github.com/allenhsu/NSDictionary-NilSafe/commit/b5271da3294019c5b912783850419b838d8d2e39 你可以看一下这个 commit，尝试用比较 hacky 的方式处理 nil block。
